% entities/Player.m
function player = createPlayer()
%CREATEPLAYER  Initializes the player struct with default attributes.

player = struct( ...
    'position',    [0, 0, 0], ... %[x,y,z]
    'angle',       0.0, ...
    'health',      100.0, ...
    'maxHealth',   100.0, ...
    'mana',        0.0, ...
    'hasKey',      false, ...
    'speed',       5.0, ... %[cell per sec]
    'animFrame',   0 ...
    );
end