% entities/Sprite.m
function sprite = createSprite(pos, typeID, state, animFrame, aiBrain, soundTag)
    %CREATESPRITE Constructs a single sprite struct.
    %
    %   sprite = createSprite([x y z], typeID, state, animFrame, aiBrain, soundTag)
    
        if nargin < 6
            soundTag = 'none';
        end
    
        sprite = struct( ...
            'pos',       [0,0,0], ...
            'typeID',    1, ...
            'health', 100.0, ...
            'state',     state, ...
            'speed', 2.0, ...
            'opacity', 1.0, ...
            'animFrame', 'healthy', ...
            'aiBrain',   'fastestPath', ...
        );
    end