% entities/Sprite.m
function sprite = createSprite(pos, type, state, animFrame, aiBrain)
%CREATESPRITE Constructs a single sprite struct.
%
%   sprite = createSprite([x y z], typeID, state, animFrame, aiBrain, soundTag)

if (type == "soldier")

    sprite = struct( ...
        'speed', 2.0,...
        'health', 20,...
        'maxHealth', 20,...
        'opacity', 1,...
        'pos',       pos, ...
        'type',    type, ...
        'state',     state, ...
        'animFrame', int32(animFrame), ...
        'aiBrain',   aiBrain
    );
else

    sprite = struct( ...
        'speed', 4.0,...
        'health', 10,...
        'maxHealth', 10,...
        'opacity', 0.4,...
        'pos',       pos, ...
        'type',    type, ...
        'state',     state, ...
        'animFrame', int32(animFrame), ...
        'aiBrain',   aiBrain
    );
end

end