function arduinoManager = createArduinoManager()
uno = arduino('COM3', 'Uno');
nano = arduino('COM4', 'Uno');

arduinoManager = struct( ...
    'uno', uno, ...
    'nano', nano, ...
    'getPos', @(self) getPos(self.uno), ...
    'writeHealth', @(self, val) writeHealth(self.nano, val), ...
    'writeKeyGhost', @(self, key, ghost) writeKG(self.nano, key, ghost) ...
    );
end