% managers/AudioManager.m
function audioManager = createAudioManager()
%CREATEAUDIOMANAGER Loads all sounds and maps them by tag

% Load and map sounds into struct
audioManager.sounds = struct( ...
    'ghostShimmer',   loadSound('assets/audio/ghost_shimmer.wav'), ...
    'enemyGroan',     loadSound('assets/audio/enemy_groan.wav'), ...
    'doorOpen',       loadSound('assets/audio/door_open.wav'), ...
    'chestOpen',      loadSound('assets/audio/chest_open.wav'), ...
    'pickupKey',      loadSound('assets/audio/pickup_key.wav'), ...
    'victoryJingle',  loadSound('assets/audio/victory.wav'), ...
    'playerHurt',     loadSound('assets/audio/player_hurt.wav') ...
    );

% A queue of strings (tags) to play each frame
audioManager.queue = strings(0, 1);
end

function y = loadSound(filepath)
% Load a sound file and return its waveform
[y, ~] = audioread(filepath);
end