% managers/InputManager.m
function inputManager = createInputManager()
%% 5) InputManager Struct
inputManager = struct( ...
    'joystick1',  [0, 0], ...      % [x,y] from readValue()
    'joystick2',  [0, 0], ...      % [x,y] from readValue()
    'shoot',     false, ...
    'interact',  false, ...
    'dropKey',   false, ...
    'deadzone',  0.1 ...
);
end